[model]
d_model = 200
nhidden = 200
nlayers = 2
nhead = 4
dropout = 0.2
[data]
year = 2016
train_split = 0.5
[train]
batch_size = 10
eval_batch_size = 10
forecast_window = 1
input_length = 50
epochs = 1000
device = "gpu"
optimizer = "Nadam"
loss = "MSE"
lr = 0.00001
exp_dir = "test"